version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ecommerce
      - JWT_SECRET=mysecurejwt
    volumes:
      - ./backend:/app  # Mount backend source code for live updates (dev only)
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app  # Mount frontend files (optional for dev)
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"  # Expose MySQL if you want to access from host (phpMyAdmin, Workbench, etc.)
    volumes:
      - mysql-data:/var/lib/mysql  # Persistent volume for DB data

volumes:
  mysql-data:
