name: Build and Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (backend)
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend

    - name: Build and push Docker image (frontend)
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/End-2-End-E-commerce_App
          git pull origin master
          docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend
          docker-compose down
          docker-compose up -d
